<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrdwsch\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrdwsch/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCrdwsch.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCrdwsch\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCrdwsch\appDevDebugProjectContainer([
    'container.build_hash' => 'Crdwsch',
    'container.build_id' => '6bb945c4',
    'container.build_time' => 1643125411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrdwsch');
