<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8hlzffx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8hlzffx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8hlzffx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8hlzffx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8hlzffx\appProdProjectContainer([
    'container.build_hash' => '8hlzffx',
    'container.build_id' => '049df207',
    'container.build_time' => 1643211933,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8hlzffx');
